openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://2r92h0rs80.execute-api.us-east-1.amazonaws.com/prod
    description: AWS API Gateway
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    description:
                      type: string
                      example: "Product Description"
                    id:
                      type: string
                      example: "1"
                    price:
                      type: number
                      example: 100
                    title:
                      type: string
                      example: "Product title"
  /products/{productId}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: string
            example: "2"
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                    example: "Product Description"
                  id:
                    type: string
                    example: "1"
                  price:
                    type: number
                    example: 100
                  title:
                    type: string
                    example: "Product title"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
