openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://sdcrglzh8d.execute-api.us-east-1.amazonaws.com/prod
    description: AWS API Gateway
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    count:
                      type: number
                      example: 10
                    price:
                      type: number
                      example: 100
                    title:
                      type: string
                      example: "Product title"
                    description:
                      type: string
                      example: "Product Description"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
    post:
      summary: Add a new product
      operationId: createProduct
      requestBody:
        description: Product to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: number
                  example: 10
                price:
                  type: number
                  example: 100
                title:
                  type: string
                  example: "New Product"
                description:
                  type: string
                  example: "New Product Description"
      responses:
        "201":
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  count:
                    type: number
                    example: 10
                  price:
                    type: number
                    example: 100
                  title:
                    type: string
                    example: "New Product"
                  description:
                    type: string
                    example: "New Product Description"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request payload
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /products/{productId}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: string
            example: "2"
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  count:
                    type: number
                    example: 10
                  price:
                    type: number
                    example: 100
                  title:
                    type: string
                    example: "Product title"
                  description:
                    type: string
                    example: "Product Description"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
